sudo: required
#dist: trusty
dist: xenial
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt install -y libgmp-dev
script:
  - git clone https://github.com/herumi/cybozulib.git
  - git clone https://github.com/herumi/xbyak.git
  - git clone https://github.com/herumi/debug_mcl.git
  - cd debug_mcl
  - make DEBUG=1 bin/fp_test.exe bin/fp_generator_test.exe
  - bin/fp_test.exe
  - bin/fp_generator.exe
#  - make test DEBUG=1
#  - make clean
#  - make test_go

 
